title: TTS Handbook
description: >- # this means to ignore newlines
  The Technology Transformation Services Handbook is an open, crowd-sourced,
  accessible, and living resource that aims to provide the information our team
  needs to do their work.

# How long of a word count before showing in page nav
inpagenavwordcount: 300
